#!/bin/fish

# --- SOURCED FILES ---

function banner
	source ../source/banner
end

function menu
	source ../source/menu $argv
end

function prmpt
	source ../source/prmpt $argv
end

# --- VARIABLES ---

set installed_files
set not_installed_files

# --- FUNCTIONS ---

function create_file_list

	set installed_files (jq -rc 'select(.installed == true).name' files.json)
	set not_installed_files (jq -rc 'select(.installed == false).name' files.json)

end

function show_installed

		set_color yellow
		echo '--- INSTALLED ---'
		set_color green

		for var in $installed_files
			echo $var
		end

		set_color yellow
		echo '--- NOT INSTALLED ---'
		set_color red

		for var in $not_installed_files
			echo $var
		end

		set_color normal
		echo '---------------------'

end

function install_file

	set target $argv
	jq --arg t $target 'select(.name == $t).installed |= true' ./files.json > ./temp.json
	if test $status -eq 0
		mv ./temp.json ./files.json
	else
		echo 'JQ Parsing error. Maybe files.json does not exist?'
	end
	create_file_list

end

function uninstall_file 

	set target $argv
	jq --arg t $target 'select(.name == $t).installed |= false' ./files.json > ./temp.json
	if test $status -eq 0
		mv ./temp.json ./files.json
	else
		echo 'JQ Parsing error. Maybe files.json does not exist?'
	end
	create_file_list

end

function update_scripts
	set_color yellow
	echo 'NOT YET IMPLEMENTED'
	set_color normal
end

function cb
	clear
	banner
end

# --- CODE ---


cb


# initialize file list
create_file_list

set_color yellow

echo 'WELCOME TO THE KIND-OF INTERACTIVE FILE INSTALLER!'

set_color normal
echo 'What would you like to do?'

while true

	menu 'See managed scripts' 'Add script to installer' 'Update scripts'

	echo \n

	switch $mswitch

		case 1
		cb
			while true
			cb
			show_installed
			menu 'INSTALL' 'UNINSTALL'
			switch $mswitch

			case 1
			cb
				set_color yellow
				echo 'Select a script to install'
				set_color normal

				menu $not_installed_files 'ALL'

				if string match -ri '\D' $mswitch
				else if test $mswitch -eq 0
				else if test $mswitch -le (math (count $lastmenu)-1)
					install_file $lastmenu[$mswitch]
				else if test $mswitch -eq (math (count $lastmenu))
				set_color brred;
				echo 'NOT YET IMPLEMENTET'
				read -P '>' 
				set_color normal
				end
			case 2
			cb
				set_color yellow
				echo 'Select a script to install'
				set_color normal

				menu $installed_files 'ALL'

				if string match -ri '\D' $mswitch
				else if test $mswitch -eq 0
				else if test $mswitch -le (math (count $lastmenu)-1)
					uninstall_file $lastmenu[$mswitch]
				else if test $mswitch -eq (math (count $lastmenu))
				set_color brred;
				echo 'NOT YET IMPLEMENTET'
				read -P '>'
				set_color normal
				end

			case '*'
			cb
				break
			end
			end
		case 2
		cb
			update_scripts
		case '*'
		cb
			echo 'Thank you for trusting in THORNEHILL64'
			break

	end

end
