#!/bin/fish

set -l go
set -l P 'Continue?'


getopts $argv | while read -l key value
	switch $key
		case P
			set P $value
	end
end

read -P $P' [Y/n]:' -n 1 go
switch $go
	case 'Y' 'y'
		exit 0
	case '*'
		exit 1
end
