#!/bin/fish

set target $argv
set switchopen false

if set -q '$argv'
	echo 'No arguments given!'
	echo 'Please give a script name to create!'
	echo 'You can also use the -o option to open the created file in $EDITOR'
	exit 1
end

if test (count $argv) -ge 3
	echo 'Too many arguments! Please only specify one file to be created'
	echo 'You can also use -o to open the created file in $EDITOR'
	exit 1
end

if contains -- '-o' $argv
	set switchopen true
	set -e target[(contains -i -- '-o' $target)]
end

if test -e ~/scripts/scripts-git/$target
	echo 'File already exists'
	exit 1
end



mkdir -p ~/scripts/scripts-git/$target
touch ~/scripts/scripts-git/$target

if test $switchopen = 'true'
	$EDITOR ~/scripts/scripts-git/$target
end
